title: Home

resources:
  - url: /hacsfiles/lovelace-fold-entity-row/fold-entity-row.js
    type: module
  - url: /hacsfiles/lovelace-card-tools/card-tools.js
    type: js
  - url: /hacsfiles/secondaryinfo-entity-row/secondaryinfo-entity-row.js
    type: module
  - url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
    type: js
  - url: /hacsfiles/lovelace-home-feed-card/lovelace-home-feed-card.js
    type: module


joint-styling: &joint-style
  style:
    .: |
      ha-card {
        border-radius: 15px;
        overflow: hidden;
        width: 98%;
        margin: 0 0;
        background-image: url("/local/cardbackK.png");
        background-repeat: no-repeat;
        background-color: rgba(50,50,50,0.3);
        background-size: 100% 68px;
        border: solid 1px rgba(100,100,100,0.3);
        box-shadow: 3px 3px rgba(0,0,0,0.4);
      }

      ha-icon {
        height: 10pt !important;
        width: 10pt !important;
      }

      name {
        font-size: smaller !important;
      }

    "#states div":
      fold-entity-row:
        $: |
          #items {
            padding: 0 0 0 0px;
            margin: 0;
            font-size: small;
          }
          #head {
            font-size: small;
          }

    .name: |
      {
        font-size: smaller !important;
      }



views:
  - id: dashboard
    title: Dashboard
    icon: mdi:home
    background: center / cover no-repeat url("/local/back.png") fixed
    cards:
      - type: glance
        <<: *joint-style
        show_state: false
        columns: 3
        entities:
          - binary_sensor.1r96d
          - binary_sensor.1r64a
          - binary_sensor.1r8rq
          - entity: binary_sensor.garage
            tap_action: 
              action: call-service
              service: cover.toggle
              service_data:
                entity_id: cover.garage_door
          - binary_sensor.39mvn
          - binary_sensor.3a8e1
          - binary_sensor.39wkr
          - binary_sensor.39n1c
          - binary_sensor.39vqk

      - type: entities
        <<: *joint-style
        show_header_toggle: false
        entities:
          - entity: input_boolean.alarm_when_away
            icon: none
          - entity: input_boolean.vacuum_when_away
            icon: none
      
      - type: entities
        <<: *joint-style
        title: Vacuum
        show_header_toggle: false
        entities:
          - input_select.vacuum_room 
          - type: custom:fold-entity-row
            head: 
              entity: vacuum.downstairs_vacuum
              name: "Downstairs"
              icon: none
              type: "custom:secondaryinfo-entity-row"
              secondary_info: "[[ sensor.downstairs_human_readable_time_since_last_run ]] ago"
            padding: 20
            entities:
              - entity: input_number.downstairs_days_between_vacuuming
                icon: none
              - entity: input_datetime.downstairs_vacuum_scheduled_runtime
                icon: none
              - entity: counter.downstairs_vacuum_run_counter
                icon: none
              - type: call-service
                name: Send vacuum to trashcan
                icon: none
                service: script.vacuum_goto_downstairs_bin
                action_name: Send
              - type: call-service
                name: Reset run counter
                icon: none
                service: counter.reset
                action_name: Reset
                service_data:
                  entity_id: counter.downstairs_vacuum_run_counter
          - type: custom:fold-entity-row
            head: 
              entity: vacuum.upstairs_vacuum
              name: "Upstairs"
              icon: none
              type: "custom:secondaryinfo-entity-row"
              secondary_info: "[[ sensor.upstairs_human_readable_time_since_last_run ]] ago"
              padding: 20
            entities:
              - entity: input_number.upstairs_days_between_vacuuming
                icon: none
              - entity: input_datetime.upstairs_vacuum_scheduled_runtime  
                icon: none
              - entity: counter.upstairs_vacuum_run_counter
                icon: none
              - type: call-service
                name: Send vacuum to trashcan
                icon: none
                service: script.vacuum_goto_upstairs_bin
                action_name: Send
              - type: call-service
                name: Reset run counter
                icon: none
                service: counter.reset
                action_name: Reset
                service_data:
                  entity_id: counter.upstairs_vacuum_run_counter

      - type: entity-filter
        card:
          type: entities
          <<: *joint-style
          title: Who's where?
          show_header_toggle: false
          show_state: false
          show_name: true
        entities:
          - !secret person1
          - !secret person2
        state_filter:
          - home
        show_empty: true

      - type: "custom:home-feed-card"
        title: Feed
        show_empty: false
        remove_repeats: false
        entities:
          - binary_sensor.1r96d
          - binary_sensor.1r64a
          - binary_sensor.1r8rq
          - binary_sensor.39ja6
          - binary_sensor.39mvn
          - binary_sensor.3a8e1
          - binary_sensor.39wkr
          - binary_sensor.39n1c
          - binary_sensor.39vqk
          - vacuum.upstairs_vacuum
          - vacuum.downstairs_vacuum


    