########################################################################
### OpenGarage.io
########################################################################



### Cover
########################################################################
cover:
  platform: opengarage
  covers:
      garage:
        host: !secret garage_internal_ip
        device_key: !secret opengarage_pass
        name: Garage_Door


### Sensors
########################################################################
binary_sensor:
  - platform: template
    sensors:
      garage:
        friendly_name: "Garage"
        device_class: garage_door
        value_template: "{{ is_state_attr('cover.garage_door', 'door_state', 'open') or is_state_attr('cover.garage_door', 'door_state', 'opening') or is_state_attr('cover.garage_door', 'door_state', 'closing') }}"

sensor:
  - platform: template
    sensors:
      garage_status:
        friendly_name: 'Garage Door'
        value_template: >-            
            {% if state_attr('cover.garage_door', 'door_state') %}
            {% if is_state_attr('cover.garage_door', 'door_state', 'open') %}
              Open
            {% elif is_state_attr('cover.garage_door', 'door_state', 'closed') %}
              Closed
            {% elif is_state_attr('cover.garage_door', 'door_state', 'opening') %}
              Opening
            {% elif is_state_attr('cover.garage_door', 'door_state', 'closing') %}
              Closing
            {% else %}
              Unknown
            {% endif %}
            {% else %}
            n/a
            {% endif %}
        icon_template: >-
            {% if state_attr('cover.garage_door', 'door_state') %}
            {% if is_state_attr('cover.garage_door', 'door_state', 'open') %}
              mdi:garage-open
            {% elif is_state_attr('cover.garage_door', 'door_state', 'closed') %}
              mdi:garage
            {% elif is_state_attr('cover.garage_door', 'door_state', 'opening') %}
              mdi:arrow-up
            {% elif is_state_attr('cover.garage_door', 'door_state', 'closing') %}
              mdi:arrow-up
            {% else %}
              mdi:question-mark
            {% endif %}
            {% else %}
            n/a
            {% endif %}



      garage_car_present:
        friendly_name: 'Car detected'
        value_template: >-
          {% if states('cover.garage_door') %}
          {% if is_state_attr('cover.garage_door', 'door_state', 'open') %} 
                        n/a
           {% elif (state_attr('cover.garage_door', 'distance_sensor') > 18) and (state_attr('cover.garage_door', 'distance_sensor') < 100) %}
                        Yes
                      {% else %}
                        No
                      {% endif %}
           {% endif %}


### Script
########################################################################
script:
  notify_if_garage_door_is_open:
    alias: Notify if garage door is open
    sequence:
    - condition: template
      value_template: "{{ is_state_attr('cover.garage_door', 'door_state', 'open') }}"
    - service: notify.notify
      data_template:
        message: >
          Garage door is open



### Automation
########################################################################
automation:
- id: notify_when_garage_door_opens_or_closes
  alias: Notify when garage door opens or closes
  trigger:
  - platform: state
    entity_id: sensor.garage_status
  condition: 
  action:
    service: notify.notify
    data_template:
      message: "Garage door is {{ state_attr('cover.garage_door', 'door_state') }}"
        